config/routes.rb
RubyChina::Application.routes.draw do
  require 'api'

  resources :sites

  resources :posts
  resources :pages, :path => "wiki" do
    collection do
      get :recent
    end
  end
  resources :comments
  resources :notes
  match "/uploads/*path" => "gridfs#serve"
  root :to => "home#index"

  devise_for :users, :path => "account", :controllers => {
      :registrations => :account,
      :omniauth_callbacks => "users/omniauth_callbacks"
    } do
    get "account/update_private_token" => "account#update_private_token", :as => :update_private_token_account
  end

  match "account/auth/:provider/unbind", :to => "users#auth_unbind"

  match "users/location/:id", :to => "users#location", :as => :location_users
  resources :users do
    member do
      get :topics
      get :favorites
    end
  end
  resources :notifications, :only => [:index, :destroy] do
    collection do
      put :mark_all_as_read
    end
  end

  resources :nodes

  match "topics/node:id" => "topics#node", :as => :node_topics
  match "topics/node:id/feed" => "topics#node_feed", :as => :feed_node_topics
  match "topics/last" => "topics#recent", :as => :recent_topics
  resources :topics do
    member do
      post :reply
      post :favorite
    end
    collection do
      get :search
      get :feed
      post :preview
    end
    resources :replies
  end

  resources :photos do
    collection do
      get :tiny_new
    end
  end
  resources :likes

  match "/search" => "search#index", :as => :search
  match "/search/wiki" => "search#wiki", :as => :search_wiki

  namespace :cpanel do
    root :to => "home#index"
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users
    resources :photos
    resources :posts
    resources :pages do
      resources :versions, :controller => :page_versions do
        member do
          post :revert
        end
      end
    end
    resources :comments
    resources :site_nodes
    resources :sites
    resources :locations
  end

  mount RubyChina::API => "/"

  if Rails.env.development?
    mount UserMailer::Preview => 'mails/user'
  end
end

app/models/note.rb
# coding: utf-8
# 记事本
class Note
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::BaseModel

  field :title
  field :body
  field :word_count, :type => Integer
  field :changes_count, :type =>  Integer, :default => 0
  field :publish, :type => Boolean, :default => false
  belongs_to :user

  index :user_id

  attr_accessible :title, :body, :publish

  default_scope :order => "id desc"

  before_save :auto_set_value
  def auto_set_value
    if !self.body.blank?
      self.title = self.body.split("\n").first[0..50]
      self.word_count = self.body.length
    end
  end

  before_update :update_changes_count
  def update_changes_count
    self.changes_count = 0 if self.changes_count.blank?
    self.inc(:changes_count,1)
  end

end

app/controllers/notes_controller.rb
# coding: utf-8
class NotesController < ApplicationController

  load_and_authorize_resource

  before_filter :init_base_breadcrumb

  def init_base_breadcrumb
    drop_breadcrumb(t("menu.notes"), notes_path)
  end

  def index
    @notes = current_user.notes.paginate(:page => params[:page], :per_page => 20)
    set_seo_meta t("menu.notes")
    drop_breadcrumb("列表")
  end

  def show
    @note =  Note.find(params[:id])
    set_seo_meta("查看 &raquo; #{t("menu.notes")}")
    drop_breadcrumb("查看")
  end

  def new
    @note = current_user.notes.build
    set_seo_meta("新建 &raquo; #{t("menu.notes")}")
    drop_breadcrumb(t("common.create"))
  end

  def edit
    @note = current_user.notes.find(params[:id])
    set_seo_meta("修改 &raquo; #{t("menu.notes")}")
    drop_breadcrumb("修改")
  end

  def create
    @note = current_user.notes.new(params[:note])

    if @note.save
      redirect_to(@note, :notice => t("common.create_success"))
    else
      render :action => "new"
    end
  end

  def update
    @note = current_user.notes.find(params[:id])

    if @note.update_attributes(params[:note])
      redirect_to(@note, :notice => t("common.update_success"))
    else
      render :action => "edit"
    end
  end

  def destroy
    @note = current_user.notes.find(params[:id])
    @note.destroy

    redirect_to(notes_url)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def render_node_topics_count(node)
    node.topics_count
  end

  def render_node_name(name, id)
    link_to(name, node_topics_path(id))
  end
end

app/views/notes/_form.html.erb
<%= simple_form_for(@note) do |f| %>
  <fieldset>
    <%= render "shared/error_messages", :target => @note %>
    <div class="inputs-list pull-right">
      <label for="note_publish"><%= f.check_box :publish %> <%= t("common.public")%></label>
    </div>
    <%= f.text_area :body, :class => "span16", :style => "height:500px" %>
    <p class="help-block">
      <%= t("notes.please_use") %> <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">Markdown</a> <%= t("notes.document_format_to_write") %>
    </p>
    <div class="buttons">
      <%= f.submit t("common.save"), :class => "btn primary", :disable_with => t("common.saving") %>
      <a href="<%= notes_path %>" class="btn"><%= t("common.cancel") %></a> 
    </div>
  </fieldset>
<% end %>

app/views/notes/_sidebar.zh-CN.html.erb
<div class="sidebar">
  <div class="box">
    <h2>记事本是什么？</h2>
    <p class="summary">这是一个基于云存储的网络记事本，你可以放心的把你的一些文本资料存放在此处。</p>
    <p>
      <a href="<%= new_note_path %>" class="btn success"><%= t("common.create") %></a>
    </p>
  </div>

  <% if ["new","edit"].index(params[:action]) %>
  <div class="box">
    <ul>
      <li>记事的第一行将自动成为标题</li>
      <li>超级链接会自动转换为可点击的状态</li>
      <li>目前只支持纯文本格式</li>
      <li>记事本的内容只有你自己才能看到</li>
    </ul>
  </div>
  <% end %>
</div>

app/views/notes/_sidebar.zh-TW.html.erb
<div class="sidebar">
  <div class="box">
    <h2>記事本是什麼？</h2>
    <p class="summary">這是一個基於雲端儲存的網路記事本，你可以放心的把你的一些文件資料存放在這裡。</p>
    <p>
      <a href="<%= new_note_path %>" class="btn success"><%= t("common.create") %></a>
    </p>
  </div>

  <% if ["new","edit"].index(params[:action]) %>
  <div class="box">
    <ul>
      <li>記事的第一行將自動成為標題</li>
      <li>超連結會自動轉換為可點擊的狀態</li>
      <li>目前只支援純文字格式</li>
      <li>記事本的內容只有你自己才能看到</li>
    </ul>
  </div>
  <% end %>
</div>

app/views/notes/edit.html.erb
<%= render 'base' %>
<div class="notes box">
  <h1><%= t("notes.edit_note")%></h1>
  <%= render 'form' %>
</div>

app/views/notes/index.html.erb
<%= render 'base' %>
<div class="content">
  <div id="notes" class="box">
    <h1>我的记事本</h1>
    <div class="total">已有 <%= current_user.notes.count %> 条记事</div>
    <% if @notes.blank? %>
      <div style="text-align:center; padding:60px 0;">你还没有创建过一个文件。</div>
    <% else %>
      <ul class="list">
      <% @notes.each do |note| %>
        <li>
          <div><a class="title" href="<%= note_path(note.id) %>"><%= truncate(note.title, :length => 50) %></a> <%= raw '<span class="label warning">公开</span>' if note.publish %></div>
          <div class="info">
            <%= note.word_count %> <%= t("notes.chars") %>, 由 <%= user_name_tag(note.user) %><%= raw t("notes.created_at", :time => timeago(note.created_at)) %> , <%= note.changes_count %> <%= t("notes.times_edit") %>
          </div>
        </li>
      <% end %>
      </ul>
    <% end %>
    <%= will_paginate @notes %>
  </div>
</div>

<%= render "sidebar" %>

app/views/notes/new.html.erb
<%= render 'base' %>
<div class="notes box">
  <h1><%= t("notes.create_note")%></h1>
  <%= render 'form' %>
</div>

app/views/notes/show.html.erb
<%= render 'base' %>
<div id="notes" class="box">
  <div class="note">
    <% if @note.publish %>
    <div class="pull-right urls">
      <em><%= t("notes.page_link")%></em> <input type="text" onclick="$(this).select();" value="<%= note_url(@note) %>" readonly="readonly" />
    </div>
    <% end %>
    <div class="info">
      <p>
        <%= raw '<span class="label warning">公开</span> ' if @note.publish %>
        共 <%= @note.word_count %> <%= t("notes.chars") %>, 由 <%= user_name_tag(@note.user) %> <%= raw t("notes.created_at", :time => timeago(@note.created_at)) %> , <%= @note.changes_count %> <%= t("notes.times_edit") %>
      </p>
    </div>

    <div class="body"><%= markdown(@note.body) %></div>
    
    <% if owner? @note %>
      <div class="buttons">
        <a href="<%= edit_note_path(@note) %>" class="btn"><%= t("common.edit")%></a>
        <%= link_to t("common.delete"), note_path(@note),:confirm => t("common.confirm_delete"), :method => :delete, :class => "btn danger"  %>
      </div>
    <% end %>
  </div>
</div>